{% set version = "0.2.1" %}
{% set checksum = "cd2d58d584c33fd00236b265148ced9a0d7acdf17904954f6e028562d4301174" %}

package:
    name: firelight
    version: {{ version }}

source:
    url: https://github.com/inferno-pytorch/firelight/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip

    run:
        - python >=3.6
        - pyyaml >=3.12
        - matplotlib-base
        - scikit-learn
        - scikit-image
        - pytorch >=0.4

test:
    imports:
        - firelight

about:
    license: Apache 2.0
    license_file: LICENSE
    license_family: APACHE
    summary: A visualization library for PyTorch tensors
    home: https://github.com/inferno-pytorch/firelight

extra:
    recipe-maintainers:
        - constantinpape
        - imagirom
