travis:
  secure:
    BINSTAR_TOKEN: AsKFMzFLUlM5+srfzQCV+Lzs/042nG7jQNf0Meue4HcFt9sXIF0vkjYaTwObIbiEbsP1gbePQucudvDc1BbgZWU74lRqIJ9Ve561H48Dr4/05nCrn7TumtRQnmYR5lsJyD2uwhEo0H/LZcKsAwchBTE1ur3gukrTpHJjQEyYcPaqzYUEmrYOoS4TBuVO3CVT1MLDi5YFXcdaqxF7KRhg67knYR2DFiOZBdrGUguqoHgaZc1IBKvPMiSbxCGTPYj+cBlGKQ/6hP+yRJa60jtfINQiy5pbU4DQQQzgOa/MLWqn9TuB4WJNCWkiftVcG6emGPGpg7ZWtpjVreUFkNSbvgqe5FgakmsXxHAAfyTkzfNoHr/UaGdyfwdsf+e0SFKy0dlQSp3nc2Pa/KfTk7UFs6Pgd7NKYk+wvRwGJzigcjKUh/HWT/I/EvyfnhIoNqh3Cqjs4L+UsJC9JC5pPbN/JTK4v5i6SzVOtNJ4l5nOvOwwhEeQEkyWtCbcr6/vra404s+zWKQzMiJPME+Vl0YY0toE3na/MBi5LYiyV7xveMY8Yi2z0eY+/M4ES5Ls2IwthlyB7C/dEu1bLmZVvdzwmE3IkFU3MMrZhiobWTME4hWb7d8FC5d6waeLt5Hag2ys9xW+fpLlZ+rI9rTLSImoWdVYjK8D7wG0lMiSgP91Wfo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
